// Generated by Wrangler by running `wrangler types`

interface Env {
  SESSION_SECRET: string;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  BASE_URL: string;
  BACKEND_URL: string;
  // biome-ignore lint/correctness/noUndeclaredVariables: <explanation>
  HONO_BACKEND_APP: Fetcher;
}
